---
name: New model request
description: Submit a new model request
title: "M@TE submission request from [@username]"
labels: ["new model"]

body:


  - type: markdown
    attributes:
      value: "## Section 1: summary of your model"


  - type: markdown
    attributes:
      value: |
        Let's start by identifying you - the person submitting the model.

  - type: input
    id: submitter
    attributes:
      label: -> submitter ORCID (or name)
      placeholder: "0000-0002-1270-4377 (Carey, Sam)"
      description: "Please provide the ORCiD (or Familyname, GivenName) associated with the person submitting the model. This is not necessarily the model creator."
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: -> slug
      placeholder: "carey-1965-expansion"
      description: "Please provide a slug for the model, using format 'familyname-year-keyword'. This will be used as the name of the model repository, and be used in URLs/DOIs. "
    validations:
      required: true

  - type: dropdown
    id: model-license
    attributes:
      label: -> model category
      description: "Select relevant fields"
        - CC-BY-4.0
        - AGPL-3.0
        - GPL-3.0
        - LGPL-3.0
        - MPL-2.0
        - Apache-2.0
        - MIT
        - BSL-1.0
        - Unlicense
        - No license
    validations:
      required: true



  - type: input
    id: alt_licence_url
    attributes:
      label: -> alternative licence URL
      description: "If an alternative (open) licence is required, please provide a URL."


  - type: dropdown
    id: about_metadata_tags
    attributes:
      label: -> model category
      description: "Select relevant fields"
      multiple: true
      options:
        - "model published in study"
        - "community benchmark"
        - "attempted reproduction"
        - "educational"
        - "forward model"
        - "inverse model"
        - "other"

  - type: dropdown
    id: status_metadata_tags
    attributes:
      label: -> model status
      description: "Select relevant fields"
      multiple: false
      options:
        - "completed"
        - "ongoing"

  - type: input
    id: pub_doi
    attributes:
      label: -> associated publication DOI
      placeholder: "https://doi.org/10.47366/sabia.v5n1a3."
      description: "By providing an associated publication DOI, we can prefill many of the remaining fields for Section 1. If no associated publication is provided, the following fields should be provided"


  - type: markdown
    attributes:
      value: |
        Who is responsible for the model?
        [CreativeWorks](https://schema.org/CreativeWork) differentiate been the primary [authors/creators](https://schema.org/author) and secondary [contributors](https://schema.org/contributor).

  - type: textarea
    id: model_creators
    attributes:
      label: -> model creators
      placeholder: "ORCID iD (or Citizen, Jane)"
      description: "Please provide ORCID iDs for the primary creators of the model (or FamilyName(s), GivenName(s)), one per line.
      If no input provided, all authors from the publication DOI will be added."

  - type: input
    id: title
    attributes:
      label: -> title
      placeholder: "title of you model"
      description: "If no input provided, info. from publication DOI will be used"

  - type: textarea
    id: description
    attributes:
      label: -> description
      placeholder: "model description"
      description: "if no input provided, info. from publication DOI will be used. Markdown formatting can be used here and will be rendered on the website."


  - type: input
    id: keywords
    attributes:
      label: -> scientific keywords
      placeholder: "keyword1, keyword2, ..."
      description: "if no input provided, info. from publication DOI will be used"

  - type: input
    id: funder_ROR_URI
    attributes:
      label: -> funder
      placeholder: "https://www.arc.gov.au/"
      description: "Please provide a ROR/URI for funding organization. Search for RORs here: https://ror.org/"

  - type: markdown
    attributes:
      value: "## Section 2: your model code, output data"

  - type: markdown
    attributes:
      value: "_Adding your model code and model output data takes place later, once your model repository has been set up!._"

  - type: input
    id: request_embargo
    attributes:
      label: -> model embargo?
      placeholder: "Leave blank if No, if YES, provide a date in the form 1964-02-29"
      description: |
        If you would like to request an embargo period, please provide an estimated end date in the form [1964-02-29] (i.e '%Y-%m-%d').
        Model submission can proceeed as normal, and you will recieve a DOI once submission is complete.
        Model components (input code, output data) will only become downloadable on the M@TE NCI collection, once the embargo has ended.

  - type: checkboxes
    id: code_include
    attributes:
      label: -> include model code ?
      options:
        - label: "yes"
      description: "Are you intending to submit code (scripts, input data, post-processing) as part of your M@TE model?"
    validations:
      required: true

  - type: input
    id: code_doi
    attributes:
      label: -> model code/inputs DOI
      placeholder: "https://doi.org/10.47366/sabia.v5n1a3."
      description: "Does your model code/input data have an existing DOI (or URL. e.g., github repo.)?"

  - type: textarea
    id: code_notes
    attributes:
      label: -> model code/inputs notes
      placeholder: "Model is setup with a Python script, model.py, with X parameter provided as an argument"
      description: "Please provide a basic description of your model code/input"

  - type: checkboxes
    id: data_include
    attributes:
      label: -> include model output data?
      options:
        - label: "yes"
      description: "Are you intending to submit your model output data as part of your M@TE model?"
    validations:
      required: true

  - type: textarea
    id: data_creators
    attributes:
      label: -> data creators
      placeholder: "ORCID iD (or Citizen, Jane)"
      description: "Please provide ORCID iDs for the person(s) who ran the computation to produce this dataset (or FamilyName(s), GivenName(s)), one per line.
      This field is relavent if a model has been re-run by someone other than the model creator. If blank this field defaults to the list of creators."

  - type: input
    id: data_doi
    attributes:
      label: -> model output data DOI
      placeholder: "https://doi.org/10.47366/sabia.x5n1a3."
      description: "Does your model output data have an existing DOI (or URL. e.g., github repo.)?"

  - type: textarea
    id: data_notes
    attributes:
      label: -> model output data notes
      placeholder: "output data primarily consists of ~ 1000 *.vtk files, each representing an output timestep, with a total size of 66 Gb."
      description: "Please provide a basic description of your output data"

  - type: input
    id: data_size
    attributes:
      label: -> model output data size
      placeholder: "Model output data have a total size of ~ 128 Gb."
      description: "Please provide an estimate of the total file size you wish to contribute."

  - type: markdown
    attributes:
      value: "## Section 3: software framework and compute details"


  - type: input
    id: software_framework_doi_uri
    attributes:
      label: -> software framework DOI/URI
      placeholder: "https://doi.org/10.5281/zenodo.7455999"
      description: |
        Software framework would typcically refer to a generic modellign code (e.g. Underworld, Badlands, Citcom, FEniCS)
        Providing a DOI here will usually allow several of the fields below to be filled. 

  - type: input
    id: software_framework_repository
    attributes:
      label: -> software framework source repository
      placeholder: "https://github.com/underworldcode/underworld2"
      description: "If the software has a public source code repository, please add it here"

  - type: input
    id: software_framework
    attributes:
      label: -> name of primary software framework (e.g. Underworld, ASPECT, Badlands, OpenFOAM)
      placeholder: "Underworld2"
      description: "If provided, the name from software framework DOI will be used"

  - type: textarea
    id: software_framework_authors
    attributes:
      label: -> software framework authors
      placeholder: "ORCID iD (or Citizen, Jane)"
      description: "Please provide ORCID iDs for software framework authors (or FamilyName(s), GivenName(s)), one per line. If no input provided, authors from software framework DOI will be used"

  - type: input
    id: software_keywords
    attributes:
      label: -> software & algorithm keywords
      placeholder: "Python, Finite element, MPI ..."
      description: "Separate keywords by comma"

  - type: input
    id: compute_doi
    attributes:
      label: -> computer URI/DOI
      placeholder: "https://doi.org/10.47366/sabia.v5n1a3."
      description: "Please provide a DOI/URI for the computation resource (if relavent)"


  - type: markdown
    attributes:
      value: "## Section 4: web material (for mate.science)"

  - type: markdown
    attributes:
      value: "In this section we will gather some information so we can display your model on mate.science. Please leave blank if you do not want this to occur. Note that files and text can be added/changed later!"



  - type: textarea
    id: web_landing_page
    attributes:
      label: -> add landing page image and caption
      placeholder: "Caption for landing page image"
      description: "Please provide a landing page image by dragging an image file into this box. Max file size is 2 Mb. JPEG, PNG, SVG, PDF, PPTX, or ZIP are supported. Please also provide a short caption."

  - type: textarea
    id: web_animation
    attributes:
      label: -> add an animation (if relevant)
      placeholder: "Caption for model animation"
      description: "Please provide an animation by dragging a file into this box. GIF, MOV, MP4 are supported. Max file size is 20 Mb. Please also provide a short caption."

  - type: textarea
    id: graphic_abstract
    attributes:
      label: -> add a graphic abstract figure (if relevant)
      placeholder: "Caption for graphic abstract"
      description: "Please provide a graphic abstract, or a figure that summariese key finding. Max file size is 2 Mb.  Please also provide a short caption."

  - type: textarea
    id: model_setup
    attributes:
      label: -> add a model setup figure (if relevant)
      placeholder: "Caption for model setup figure"
      description: "Please provide a  model setup image by dragging an image file into this box. Max file size is 2 Mb.  Please also provide a short caption."

  - type: textarea
    id: model_setup_description
    attributes:
      label: -> add a description of your model setup
      placeholder: "The model uses a cartesian domain, with size 200 km x 200 km x 300 km."
      description: "Please provide add a brief (< 300 words) description of your model setup, boundary condition, assumptions. Markdown formatting can be used here and will be rendered on the website."

  - type: markdown
    attributes:
      value: "## Section 5: Feeback and next steps"

  - type: markdown
    attributes:
      value: |
        Thanks for submitting a new model to the M@TE collection. 
        This information provided in this form will enable us to produce a metadata file for your model, and showcase the model on our website.
        The [README.md](https://github.com/ModelAtlasofTheEarth/Model_Submission/blob/main/README.md) file in this repository provides an overview of the remaining model subission steps.
        Once you click submit, Github actions will parse this form, collect existing metadata, and produce a summary report for your model. 
        You can maintain a conversation with the M@TE team via the issue thread. 

  - type: textarea
    attributes:
      label: Please provide any feedback on the model submission process?
      placeholder: "Did you find any terminology confusing? Did you have issues with adding files? Is there important information about your model that that we didn't collect?"
        

