---
name: New model request
description: Submit a new model request
title: "M@TE submission request from [@your-github-username]"
labels: ["test -don't use"]

body:

  - type: markdown
    attributes:
      value: "## Section 1: Summary of your model"

  - type: markdown
    attributes:
      value: |
        Let's start by identifying you, the person submitting the model.

  - type: input
    id: submitter
    attributes:
      label: "Submitter ORCID (or name)"
      placeholder: "e.g., 0000-0002-1270-4377 (or, Carey, Sam)"
      description: "Please provide the ORCID (or Family name, Given name) associated with the person submitting the model. This is not necessarily the model creator."
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: "Slug"
      placeholder: "e.g., carey-1965-expansion"
      description: "Please provide a slug for the model, using the format 'familyname-year-keyword'. This will be used as the model repository name and in URLs/DOIs."
    validations:
      required: true

  - type: dropdown
    id: model-license
    attributes:
      label: "License"
      description: "To include your model in the [M@TE collection](https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/home) (and receive a DOI), you must select an open license. The recommended license for datasets is [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/deed.en). Please choose one of the following open licenses or supply a URL for a license (preferably a link to license text) in the box below. By selecting a license, you are warranting that you are the model owner and/or have the right to publish the model under the chosen open license. This license will cover all submitted files/data unless specified otherwise."
      options:
        - CC-BY-4.0
        - AGPL-3.0
        - GPL-3.0
        - LGPL-3.0
        - MPL-2.0
        - Apache-2.0
        - MIT
        - BSL-1.0
        - Unlicense
        - Alternative
    validations:
      required: true

  - type: input
    id: alt_license_url
    attributes:
      label: "Alternative license URL"
      description: "If an alternative (open) license is required, please provide a URL."

  - type: dropdown
    id: about_metadata_tags
    attributes:
      label: "Model category"
      description: "Select relevant fields"
      multiple: true
      options:
        - "Model published in study"
        - "Community benchmark"
        - "Attempted reproduction"
        - "Educational"
        - "Forward model"
        - "Inverse model"
        - "Other"

  - type: dropdown
    id: status_metadata_tags
    attributes:
      label: "Model status"
      description: "Select relevant fields"
      multiple: false
      options:
        - "Completed"
        - "Ongoing"

  - type: input
    id: pub_doi
    attributes:
      label: "Associated publication DOI"
      placeholder: "e.g., https://doi.org/10.47366/sabia.v5n1a3."
      description: "By providing an associated publication DOI, we can prefill many of the remaining fields for Section 1. If no associated publication is provided, the following fields should be filled out."

  - type: markdown
    attributes:
      value: |
        Who is responsible for the model?
        [CreativeWorks](https://schema.org/CreativeWork) differentiate between primary [authors/creators](https://schema.org/author) and secondary [contributors](https://schema.org/contributor).

  - type: textarea
    id: model_creators
    attributes:
      label: "Model creators"
      placeholder: "e.g., ORCID iD (or Citizen, Jane)"
      description: "Please provide ORCID iDs for the primary creators of the model (or Family name, Given name), one per line. If no input is provided, all authors from the publication DOI will be added."

  - type: input
    id: title
    attributes:
      label: "Title"
      placeholder: "e.g., Title of your model"
      description: "If no input is provided, information from the publication DOI will be used."

  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: "This model was developed in order to...."
      description: "A brief model description. Preferably plain language and less than 100 words."
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: "Abstract"
      placeholder: "Your scientific abstract"
      description: "If no input is provided, the abstract from the publication DOI will be used. Markdown formatting can be used here and will be rendered on the website."

  - type: input
    id: keywords
    attributes:
      label: "Scientific keywords"
      placeholder: "e.g., keyword1, keyword2, ..."
      description: "If no input is provided, information from the publication DOI will be used."

  - type: textarea
    id: funder_ROR_URI
    attributes:
      label: "Funder"
      placeholder: |
        https://www.arc.gov.au/, myGrant#id
        Another funding body
        https://ror.org/021nxhr62, another_grant_ID
      description: |
        Comma-separated lines in the form "funding body, grant_id".
        **Funding body** is preferably an ROR URL, but can also be an organizational URL or simply a name in plain text.
        Search for RORs here: https://ror.org/
        The **grant_id** part is optional.

  - type: markdown
    attributes:
      value: "## Section 2: Your model code and output data"

  - type: markdown
    attributes:
      value: "_Adding your model code and model output data takes place later, once your model repository has been set up!._"

  - type: input
    id: request_embargo
    attributes:
      label: "Model embargo?"
      placeholder: "Leave blank if No. If YES, provide a date in the form e.g., 1964-02-29"
      description: |
        If you would like to request an embargo period, please provide an estimated end date in the form [1964-02-29] (i.e., '%Y-%m-%d').
        Model submission can proceed as normal, and you will receive a DOI once the submission is complete.
        Model components (input code, output data) will only become downloadable in the M@TE NCI collection once the embargo has ended.

  - type: checkboxes
    id: code_include
    attributes:
      label: "Include model code?"
      options:
        - label: "yes"
      description: "Are you intending to submit code (scripts, input data, post-processing) as part of your M@TE model?"
    validations:
      required: true

  - type: input
    id: code_doi
    attributes:
      label: "Model code/inputs DOI"
      placeholder: "e.g., https://doi.org/10.47366/sabia.v5n1a3."
      description: "Does your model code/input data have an existing DOI (or URL, e.g., GitHub repo)?"

  - type: textarea
    id: code_notes
    attributes:
      label: "Model code/inputs notes"
      placeholder: "e.g., Model is set up with a Python script, model.py, with X parameter provided as an argument."
      description: "Please provide a basic description of your model code/input."

  - type: checkboxes
    id: data_include
    attributes:
      label: "Include model output data?"
      options:
        - label: "yes"
      description: "Are you intending to submit your model output data as part of your M@TE model?"
    validations:
      required: true

  - type: textarea
    id: data_creators
    attributes:
      label: "Data creators"
      placeholder: "e.g., ORCID iD (or Citizen, Jane)"
      description: "Please provide ORCID iDs for the person(s) who ran the computation to produce this dataset (or Family name, Given name), one per line. This field is relevant if a model has been rerun by someone other than the model creator. If blank, this field defaults to the list of creators."

  - type: input
    id: data_doi
    attributes:
      label: "Model output data DOI"
      placeholder: "e.g., https://doi.org/10.47366/sabia.x5n1a3."
      description: "Does your model output data have an existing DOI (or URL, e.g., GitHub repo)?"

  - type: textarea
    id: data_notes
    attributes:
      label: "Model output data notes"
      placeholder: "Output data primarily consists of ~1000 *.vtk files, each representing an output timestep, with a total size of 66 Gb."
      description: "Please provide a basic description of your output data."

  - type: input
    id: estimated_size
    attributes:
      label: "Model estimated size"
      placeholder: "Estimated size of your M@TE model (Gb)"
      description: "Include model code/input and output data. This will help us plan storage needs."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Section 3: Final steps before submission!"

  - type: markdown
    attributes:
      value: |
        ### Final checks
        - If your model has a publication DOI, metadata fields will be completed on the model creation.
        - When ready to submit, provide a few more checks and comments here.

  - type: textarea
    id: known_issues
    attributes:
      label: "Known issues"
      placeholder: "Your final checks"
      description: |
        Please describe any known issues associated with your model that could impact its reproduction or validation (e.g., 'There is a small boundary artifact that is visible in the NW corner due to assumptions made in parameterization'). This information will help future users of your model.
