name: Edit Issue Trigger
on: 
  issues:
    types: 
      - edited
jobs:
  parseEditedIssue:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # setup python
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt

      # generate report
      - name: generate report
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 .github/scripts/write_report.py

      # steps if failure
      - name: workflow url
        if: failure()
        id: workflow-url
        run: |
          echo "workflow_url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: comment on failure
        if: failure()
        uses: GrantBirki/comment@v2.0.8
        with:
          issue-number: ${{ github.event.issue.number }}
          file: .github/templates/parse-workflow-fail.md
          vars: |
            workflow_url: ${{ steps.workflow-url.outputs.workflow_url }}

      - name: add fail label
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: workflow_error
    